#Save the division of images into patches
np.save("x_train.npy", x_train)
np.save("x_test.npy", x_test)
np.save("y_train.npy", y_train)
np.save("y_test.npy", y_test)
np.save("all_patch_train.npy", all_patch_train)
np.save("label_patch_train.npy", label_patch_train)
np.save("nbr_patch.npy", nbr_patch)
np.save("all_patch_test.npy", all_patch_test)
np.save("label_patch_test.npy", label_patch_test)

#np.save("x_train_i.npy", x_train)
#np.save("x_test_i.npy", x_test)
#np.save("y_train_i.npy", y_train)
#np.save("y_test_i.npy", y_test)
#np.save("all_patch_train_i.npy", all_patch_train)
#np.save("label_patch_train_i.npy", label_patch_train)
#np.save("nbr_patch_i.npy", nbr_patch)
#np.save("all_patch_test_i.npy", all_patch_test)
#np.save("label_patch_test_i.npy", label_patch_test)

#np.save("x_train_s.npy", x_train)
#np.save("x_test_s.npy", x_test)
#np.save("y_train_s.npy", y_train)
#np.save("y_test_s.npy", y_test)
#np.save("all_patch_train_s.npy", all_patch_train)
#np.save("label_patch_train_s.npy", label_patch_train)
#np.save("nbr_patch_s.npy", nbr_patch)
#np.save("all_patch_test_s.npy", all_patch_test)
#np.save("label_patch_test_s.npy", label_patch_test)
